### ISSUE TITLE
Dependencies of TestNG tests

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#117]
Tests developed in TestNG have dependencies. Some of these are shared by several tests and some depend on each other. For example

| WFS 2.0 (r18) | GML 3.2.1 (1.20) | CAT 3.0 (0.7) |
| --- | --- | --- |
| schema-utils-1.5.jar | schema-utils-1.5.jar | schema-utils-1.6.jar |
| ets-gml32-3.2.1-r18.jar |  |  |
| jersey-client-1.18.1.jar | jersey-client-1.19.jar | jersey-client-1.19.jar |

How to better build TEAM Engine to avoid issues with classes clashing?

Ideas:
- Should we move the dependent jars to a new project?
- Should we re-build the tests every time there is a change in dependencies?
  or ?

**Comment by rjmartell** [comment]
It is usually safe to use the latest release of a given library and remove older versions from the classpath. There can be exceptions of course (especially between major releases), but I have yet to encounter any.

Note that when test suite dependencies are assembled using the scripts in the [ets-resources](https://github.com/opengeospatial/ets-resources) project, only the latest versions are retained.

**Comment by rjmartell** [comment]
JAR files are not intrinsically unique. Using standard class loading facilities only one version of a library is available at runtime (generally the first one found). The OSGi framework offers one modularity solution of long standing.

**Comment by dstenger** [comment]
In long term, we must find a solution for this problem.

There are more and more TestNG test suites using Java libraries leading to an increase number of conflicts. This can lead to unstable installations of single test suites (e.g. when API changes between different versions of Java libraries, single tests will not work any more).

So, a general concept must be developed to prevent conflicts between different dependency versions. Otherwise, installations with multiple test suites will become unstable.

**Comment by dstenger** [comment]
Usage of OSGi should be considered.

**Comment by lgoltz** [comment]
Some references about mvn and OSGi:
 * [The Maven Cookbook Chapter 1. Cooking with Maven and OSGi](https://books.sonatype.com/mcookbook/reference/osgi.html)
 * [Starting with OSGI with Maven and Spring, and understanding OSGI dependency problems](http://www.integratingstuff.com/2012/07/29/starting-with-osgi-with-maven-and-spring-and-understanding-osgi-dependency-problems/)

**Comment by ghobona** [comment]
This issue duplicates one in cite-private.
