### ISSUE TITLE
Improve testng report (test descriptions)

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#127]
## Components on each test in the testng report
- name of the test
- details based on the specification (see next header)
- reason of failure 
- how can it be fixed

## Relate testng report results to javadocs
When a user runs a testng test, the result doesn't displays information in the specification (e.g. details about the conformance class). We need to present that information to the tester. I think this information is in the javadocs.

**Comment by rjmartell** [comment]
Each test method should include a description property that refers to the applicable test requirements (e.g. abstract test case) in the specifications. It appears in a `@Test` annotation like so:

    @Test(description = "See ISO 19143: 7.8.3.2, A.7")

This bare-bones descriptive info will be included in the results (and HTML report). However, the Javadoc comments for the test method are more detailed, and it would be nice to also link to these since they are usually available online via GitHub pages. For example, see the Javadocs for the [WFS 2.0 test suite ](http://opengeospatial.github.io/ets-wfs20/apidocs/).

**Comment by rjmartell** [comment]
Test developers can insert link markup into the description property, but because it's interpreted as a string value the markup is escaped in the test results; if it were decoded in the HTML report it would appear as an active link.

Another possibility is to automatically insert the link when generating the report. This should be possible using information in the source test results; specifically, these elements:

    <suite name="wfs20-1.20">
    <class name="org.opengis.cite.iso19142.basic.filter.BBOXOperatorTests">
    <test-method signature="invalidGeometryOperand(javax.xml.namespace.QName)..."

The [corresponding link](http://cite.opengeospatial.org/te2/about/wfs/2.0.0/site/apidocs/org/opengis/cite/iso19142/basic/filter/BBOXOperatorTests.html#invalidGeometryOperand(javax.xml.namespace.QName)) could then be constructed.

**Comment by rjmartell** [comment]
The Javadocs are assumed to be available at GitHub Pages. The base URL is constructed as follows:

   `http://opengeospatial.github.io/ets-$etsCode/apidocs`

e.g. http://opengeospatial.github.io/ets-gml32/apidocs/
