### ISSUE TITLE
Internal DTD subset is ignored

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#135]
If a DOCTYPE declaration includes an internal subset that extends (or overrides) an external DTD, the internal declarations are ignored in `com.occamlab.te.parsers.XMLValidatingParser`. This only affects testing of WMS 1.1 implementations that use the (optional) [VendorSpecificCapabilities element](/opengeospatial/ets-wms11/issues/36) in the capabilities document.

**Comment by bermud** [comment]
@rjmartell, if we fix this one, do we require to do any change in the WMS 1.1 test?

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 

Following are my findings:

1. The referred issue in the first comment is occurring due to the undeclared `VendorSpecificCapabilities` element in the [DTD](http://schemas.opengis.net/wms/1.1.1/capabilities_1_1_1.dtd). I think the response may contain `VendorSpecificCapabilities` element either zero or one time according to DTD but the declaration of that element is missing. So the XMLValidatingParser gives below error: `Element type "VendorSpecificCapabilities" must be declared.`

2. The method [validateAgainstDTDList](https://github.com/opengeospatial/teamengine/blob/7b6c97a7a1c1fb0233209b39261f3d187363b8c6/teamengine-core/src/main/java/com/occamlab/te/parsers/XMLValidatingParser.java#L445-L484) in XMLValidatingParser works as below: 
    1. There are two ways to provide DTD's to the validator: a) Through CTL test implementation b) Service response has DTD with the declaration of `DOCTYPE` 
    2. Current Implementation: 
        1. If the response document and CTL test (both) have DTD document then the validator will use DTD from the CTL test and ignoring the response document DTD. 
        **Which DTD should pick/ignore by the validator?**
        2. If the response document has DTD document and CTL test does not provide any DTD, the response will be validated using the response document DTD.

**Comment by ghobona** [comment]
The ETS appears to be correctly following the DTD.

The absence of the `VendorSpecificCapabilities` declaration needs to be addressed by the SWG.

There is a related issue in the [Standards Tracker Change Request System](http://ogc.standardstracker.org/show_request.cgi?id=423).

This ETS issue is therefore closed.
