### ISSUE TITLE
Inherited failure when subtests are skipped

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#141]
When testing this server in TE 4.4 and WMTS 0.6
http://192.71.92.21/MapService/wmts.axd/Vmap0WMTS?Service=WMTS&request=GetCapabilities
We get the following results
![wmts-f1](https://cloud.githubusercontent.com/assets/3738898/11691118/a1687d40-9e67-11e5-816d-2a33197d7193.jpg)

and 

![wmts-f2](https://cloud.githubusercontent.com/assets/3738898/11691121/a325f52c-9e67-11e5-91cc-add1d5d635a5.jpg)

inherit failure seems incorrect

Logs:
[srv-6.zip](https://github.com/opengeospatial/teamengine/files/57028/srv-6.zip)

Is this an issue of TE or WMTS?

**Comment by rjmartell** [comment]
The occurrence of child skip verdicts seems to taint the parent test (group). Even if all constituent tests are skipped the parent result is **InheritedFailure** (5). The attached CTL script (skipped.txt) demonstrates this anomalous behavior:

1. input: 103 (odd integer > 100) ==> All subtests skipped, but InheritedFailure
2. input: 41 (odd integer < 100) ==> 1 skip, 1 pass, but InheritedFailure

[skip.txt](https://github.com/opengeospatial/teamengine/files/71183/skip.txt)

**Comment by bermud** [comment]
@keshav-nangare Please investigate.

**Comment by bermud** [comment]
Assuming parent is madatory:
If some subtest are skipped but at least one subtest is passing then parent test should pass.
If all subtests are skipped then parent fails.

**Comment by bermud** [comment]
Here is a more comprehensive analysis of when an InheritedFailure should occur: https://github.com/opengeospatial/teamengine/wiki/When-should-Inherited-Failure-occur
Please create several example CTL files and create unit test.

**Comment by lgoltz** [comment]
I've tried to verify the fix in the branch https://github.com/opengeospatial/teamengine/tree/feature-issue-141. The new UnitTest VerifyTECoreResults looks fine and tests the status of the parent test as documented in https://github.com/opengeospatial/teamengine/wiki/When-should-Inherited-Failure-occur. The test is successful if it is executed as single test but fails if the complete teamengine (or teamengine-core) is build. This is caused by declaring the new field subTestArray as static.

**Comment by bermud** [comment]
@lgoltz, Thank you for looking at this issue.
@keshav-nangare please look at the @lgoltz comment and make appropriate fixes. Thank you!

**Comment by keshav-nangare** [comment]
@lgoltz  Thanks for the info.

The branch feature-issue-141 didn't have the appropriate fix yet for the inherited failure. Last time we have tried to fix that issue but it was not completed and we have created the Unit tests cases with different types of the results scenario.  About the new field "subTestArray" it was declared to get all the sub-test result.

If we executed the Unit Tests "VerifyTECoreResults" with the current master then maybe we can understand the exact issue.

**Comment by lgoltz** [comment]
We created a new feature branch in our own repository based on your feature branch and merged the current master into (https://github.com/lat-lon/teamengine/tree/feature-issue-141).  Then we declared the  field "subTestArray" as _private_  instead of _public static_ (mvn clean install was successful) and tested with two services.

The result
 for http://192.71.92.21/MapService/wmts.axd/Vmap0WMTS?Service=WMTS&request=GetCapabilities  looks fine:
![wmts1_1](https://cloud.githubusercontent.com/assets/3007848/17322689/f54a94c4-589e-11e6-9633-a69a7a5eaafe.png)
![wmts1_2](https://cloud.githubusercontent.com/assets/3007848/17322644/bb78b4ec-589e-11e6-832b-6aadfab9a060.png)

But in the one for http://cite.deegree.org/deegree-webservices-3.4-RC1/services/wmts100?service=WMTS&request=GetCapabilities one of the groups have an unexpected status:
![wmts2_1](https://cloud.githubusercontent.com/assets/3007848/17322694/fbff90c6-589e-11e6-9113-55c5db66a4c2.png)
![wmts2_2](https://cloud.githubusercontent.com/assets/3007848/17322698/fe38dc58-589e-11e6-92cf-9118ef50f400.png)

The result of the Test wmts:GetCapabilities.Implemented.KVP.GET should be passed (as all of the tests have the type MandatoryIfImplemented).

Do you agree so far?

**Comment by bermud** [comment]
_MandatoryIfImplemented_ means that if the getCapabilities advertises that set of tests (e.g. a profile) is implemented (e.g. GetFeatureInfo SOAP), then it should be implemented and the test should be executed. It depends on the getCapabilities, not the parent.

If GetCapabilities 
- advertises the support for ChildTestA and they are all skipped, then the test should fail. 
- do not advertises the support for ChildTestA, then it should be marked as skipped (it should not failed)

Similar for ChildTestB

If GetCapabilities 
- advertises the support for ChildTestB and they are all skipped, then the test should fail. If ChildTestB1, ChildTestB2 and ChildTestB3 are all options, then ChildTestB should pass, because at least one option was implemented
- do not advertises the support for ChildTestB, then it should be marked as skipped. The results should never get to pass, because the test should never be executed.

**Comment by bermud** [comment]
WMTS test was simplified removing the optional tests. WMTS test is the only test using this MandatoryIfImplemented condition. We can work on this issue later.

**Comment by bermud** [comment]
Those tests were removed from WMTS 1.0. See https://github.com/opengeospatial/ets-wmts10/pull/28
