### ISSUE TITLE
Merge security fixes from WiSC

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#158]
Chuck will provide a pull request very soon related to HP Fortify fixes

**Comment by cmheazel** [comment]
Took a while to work out the process but you should have it now.

**Comment by rjmartell** [comment]
The JAXP secure processing feature "instructs JAXP components such as parsers, transformers and so on to behave in a secure fashion". Exactly what it restricts is a bit unclear, and may be implementation-dependent. See:

* https://jaxp.java.net/1.5/JAXP1.5Guide.html 
* https://jaxp.java.net/docs/spec/pdf/JAXP1_6-FinalSpec.pdf 

Unit tests will likely be required to verify expected behavior.

**Comment by rjmartell** [comment]
Merged [PR-163](/opengeospatial/teamengine/pull/163).
