### ISSUE TITLE
4.8 not building due to teamengine-virtualization because of dependencies to ets-wfs20

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#185]
TE 4.8 is not building. Here is the error. It seems to assume that WFS-2.0 is already installed and build. 

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 1.130 s
> [INFO] Finished at: 2016-08-12T06:47:32-04:00
> [INFO] Final Memory: 13M/245M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project teamengine-virtualization: Could not resolve dependencies for project org.opengis.cite.teamengine:teamengine-virtualization:pom:4.8: The following artifacts could not be resolved: org.opengis.cite:ets-wfs20:zip:ctl:1.22, org.opengis.cite:ets-wfs20:zip:eps:1.22: Could not find artifact org.opengis.cite:ets-wfs20:zip:ctl:1.22 in opengeospatial-cite (https://svn.opengeospatial.org/ogc-projects/cite/maven) -
>

**Comment by dstenger** [comment]
We also recently discovered the problem.

A workaround is to either build ets-wfs20 tag 1.22 on the same machine (dependency will be saved in local repository) or to exclude the whole module from build.

Of course, we have to find a general solution. I would propose to bind the dependency to a certain maven profile so that it is just needed if the profile is activated.

**Comment by dstenger** [comment]
Maybe, the dependency should even be excluded from the project. But then Docker cannot be started with a working ETS.

Also, @rjmartell the org.opengis.cite:ets-wfs20:zip:ctl could be uploaded to the central Maven repository. Currently, just the Java dependencies of the ets-wfs20 can be found there.

**Comment by dstenger** [comment]
Pull request was created (removes all dependencies to ets-wfs20): #186

**Comment by dstenger** [comment]
PR #186 should be merged. Otherwise, the Docker build does not work any more.

In addition, we should figure out a way how to include ETS in the Docker module (e.g. via Maven profiles). Otherwise the big advantage of using docker won't come visible (as TEAM Engine on Docker cannot be used for CITE testing).
