### ISSUE TITLE
Invoke CTL test suite via RESTful API

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#190]
This is already possible with TestNG suites, but any OGC test suite should be runnable in this manner. It will then become much easier to a) separate test suite execution from test session management, and b) enable interworking between test suites (including profiles) irrespective of how they're implemented. See the wiki page about the [notional architecture](https://github.com/opengeospatial/teamengine/wiki/Architectural-enhancements-%28teamengine-v5%29) for more information.

Related issues:
- #111

**Comment by rjmartell** [comment]
The `teamengine-spi` module declares these two interfaces:

- com.occamlab.te.spi.executors.TestRunExecutor
- com.occamlab.te.spi.jaxrs.TestSuiteController

A TestNG suite uses implementations of these interfaces in order to provide a simple RESTful API for executing a test run. A CTL suite would need to behave in a similar fashion.

**Comment by rjmartell** [comment]
The teamengine-spi-ctl module provides a `CtlExecutor` that can be used to run a CTL test suite.

**Comment by bermud** [comment]
From Richard 2006.09.23

The purpose is to demonstrate the execution of a CTL suite using a RESTful API as is possible with a TestNG suite. Just like a TestNG suite, there are three ways to run it:

1. Using an IDE (main class: CtlController) 
2. Using a CLI (console/terminal): java -jar *-aio.jar (but see note [1] below)
3. Using a RESTful API: 

a) /teamengine/rest/suites  (get list of available test suites) 

b) /teamengine/rest/suites/{ets-code}/{version}  (get test suite description: XHTML syntax) 

c) /teamengine/rest/suites/{ets-code}/{version}/run?p1=v1  (test run controller) 

e.g. 
/teamengine/rest/suites/alpha/0.9/run?input=41


NOTES:

[1] CTL scripts cannot currently be read from a JAR file, since the Generator (from the core module) only accepts File objects (FIXME). Put the script(s) in TE_BASE/scripts as is done now.

[2] Client apps can discover the recognized test run arguments in the test suite description (3b above); each argument is declared in a table row (//table[@id="arguments"]/tbody/tr).

[3] The suite depends on teamegine-spi-ctl, a new teamengine module (at the moment it only defines the CtlExecutor class).


TODO:

* Transform report_logs.xml (doc element: <execution>) to EARL report (RDF/XML) 
* Enhance the WMS 1.3 test suite using ets-alpha as a model (ignore the manual verification tests in the WMS suite--maybe these can be automated in the future using some kind of image comparison algorithm)

**Comment by keshav-nangare** [comment]
I tried to execute the ets-example test with the latest changes of teamengine through the REST API, but I am not able to run it.

I have extracted the test-suite (ets-example.zip) and placed into the "TE_BASE/script/" and tried to execute through the REST, when I tried this URL "http://localhost:8080/teamengine/rest/suites/alpha/1.0" it shows the message like "Test suite overview not found.".

Can you please provide the steps to run this ets-example test.

**Comment by rjmartell** [comment]
This sample suite depends on teamengine-spi-ctl-4.9-SNAPSHOT, so that should be built and installed first. I forgot to update the dependencies in the POM for teamengine-web (commit was pushed).

Then extract the archive and run `mvn package`. Put ets-alpha-*.jar in TE_BASE/resources/lib and unpack *-ctl.zip in TE_BASE/scripts. Start Tomcat and the suite should show up in the list at `/rest/suites`. Follow the link to view the test suite description (including test run arguments).

**Comment by rjmartell** [comment]
The response entity is the CTL output (`<execution>`) with the XInclude links dereferenced. This should be represented as EARL/RDF before too long :-)

**Comment by rjmartell** [comment]
The ctl:suite tag does not contain a ctl:form element that is parsed to present a form requesting input arguments. Instead, the arguments are read from an XML properties file just as for a TestNG suite; this document is built from the parameters in the service (/run) request.

**Example:**
/teamengine/rest/suites/alpha/0.9/run?input=41

The corresponding properties document contains an entry for each argument; it's then passed to the TestRunExecutor:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties version="1.0">
  <entry key="input">41</entry>
</properties>
```

**Note**: When running in an IDE or terminal, the default location of the properties file is `${user.home}/test-run-props.xml` but an alternative location can be specified.

**Comment by rjmartell** [comment]
The CTL test verdicts are not defined in the W3C EARL vocabulary so they can't be added there.
Define them as CITE vocabulary terms instead.

**Comment by bermud** [comment]
@rjmartell , Are these not correct veredicts?
 earl:Pass, earl:Fail, earl:CannotTell, earl:NotApplicable, earl:NotTested

**Comment by keshav-nangare** [comment]
@rjmartell 

Can please look into above Luis comment, if it is fine then I will remove that resource from the vocabulary.

**Comment by rjmartell** [comment]
I moved the CITE verdicts to `com.occamlab.te.spi.vocabulary.CITE` (e.g. cite:inheritedFailure). I suggest that cite:notTested be mapped to earl:untested. Inherited failures apply only to a test group in which one or more child tests failed; so this really corresponds to conformance class, and can thus be ignored (it's the constituent "atomic" tests that are of interest here).
