### ISSUE TITLE
Button for downloading session logs is not available

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#191]
When testing this file with the geopackage test, the button to download the logs is not showing

http://www.geopackage.org/data/simple_sewer_features.gpkg

See example of logs:
http://cite.opengeospatial.org/pub/cite/files/fhoubie-20160921.zip 

TEAM Engine 4.8.1
Geopackage Test 0.3

**Comment by bermud** [comment]
@keshav-nangare, I know you found why the button is not showing because of  missing information. The issue to be investigated is what was the reason that  TE created an incomplete session.

**Comment by keshav-nangare** [comment]
The TE creates the correct and complete session. The issue is with the **sourceId** attribute from the session.xml file.

If we observed value of **sourceId** in following session information:
```
<session id="s0004" sourcesId="OGC_GeoPackage_1.0_0.2" date="2016/09/09  07:58:57"  >
<suite>{http://www.opengis.net/cite/gpkg10}ets-gpkg10-0.2</suite>
<description></description>
</session>

```

In above session the version of the gpkg10 is **0.2** (older version session) and the current version of the gpkg10 is 0.3.

When we are viewing the result of above session then TE tries to map the sourceId with the current sourceId, but in this situation they are different.  So the viewSessionLog.jsp page is breaking in the middle, that's why the download logs button is not showing in this case and it shows the text like "error: suitEntry is null".

We have to update the session.xml file in such way that while creating the session.xml file we have to make sure that **sourceId** should not bounded with the version.

**Comment by bermud** [comment]
Maybe create a UUID for the session ID
