### ISSUE TITLE
Implement display of hierarchies in new HTML report of TEAM Engine

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#319]

**Comment by lgoltz** [comment]
Proposal for a first draft:
 * In the new HTML report (based on CTL) the test on the first level shows the result of the group but does not display the complete hierarchy. A reference to the detailed test report could be helpful.

@keshav-nangare Are changes or enhancements in the EARL report required to display hierarchies?

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please check the steps required to display hierarchies?
Do we just have to adjust the XSLT transformation?

**Comment by keshav-nangare** [comment]
Steps to display hierarchies:

1. Need to update the EARL document with the parent-child relation of the test.
2. Update XSLT transformation to convert it to HTML.
3. Need to think about how to represent the hierarchy of test in the HTML page.

**Comment by lgoltz** [comment]
> 1. Need to update the EARL document with the parent-child relation of the test.

This is already done in branch https://github.com/opengeospatial/teamengine/tree/hierarchiesInNewHtmlReport-319.

Besides the enhancements to display hierarchies, the class CtlEarlReporter was formatted and refactored. Furthermore some bugs was fixed:
 * Include  of http:Request as child of a TestResult (was child of the root element)
 * Output of the response (was empty)
 * Increasing of the number of passed tests (was 0 in each case)

**Comment by lgoltz** [comment]
Added Unit Tests for CtlEarlReporter and fixed some more bugs.

**Comment by lgoltz** [comment]
The xslt script transforming the EARL report to the new HTML report was adjusted to display the hierarchies (currently the test cases are indented on the main page, dependent on the level of the hierarchy depth).
UnitTest was added to test the transformation (therefore the code was moved from class TECore to a new class (EarlToHtmlTransformer).

As the generated EARL report seems to differ if the report is created multiple times from the same source there was missing test cases. This was fixed in  https://github.com/opengeospatial/teamengine/commit/47028b61a2136ad2b7e0438f3f071d999f220ee5

Handling of inheritedFailures was added within https://github.com/opengeospatial/teamengine/commit/cf53e2a6c82fe562c2866a33aee1a6d5978641e3. For a consistent working with the URLs provided by EARL and added with the CITE enhancements the URLs should be adjusted. Ticket #326 was created, the URL for the InheritedFailures was already adjusted in https://github.com/opengeospatial/teamengine/commit/149d8278f5d89fedd54a54ee7c586a9e7742bd96

**Comment by lgoltz** [comment]
Simplified calculation of test (was counted by the TestCase/Assertions and did not work with test hierarchies): 
https://github.com/opengeospatial/teamengine/commit/f47406913214af7342ce065a885787deee8232f3

**Comment by lgoltz** [comment]
Fixed calculation of executed tests (included inherited tests): https://github.com/opengeospatial/teamengine/commit/d53f4b4d000ecee6d4daa214c6e628e861fdd9d3

**Comment by lgoltz** [comment]
Implementation is finished so far. Currently tests without subtests (like data-preconditions in ETS WMS 1.3) contains no test results. How can we handle this?

The number of tests differs from the one  in the old report as the first (main:main) and second (data-independent, data-preconditions, basic and queryable) levels tests are not included in the new html report. Furthermore inherited failures are not marked but counted as usually failures.

**Comment by dstenger** [comment]
@keshav-nangare Can you please review the implementation and provide feedback if you identify any improvements?

**Comment by lgoltz** [comment]
>ERROR: The result is not showing in the testDetails page whether the test is passed or failed etc,

Should be fixed with https://github.com/lat-lon/teamengine/commit/aef2fa6efe2290bb3c9f718a919422018e9cbb95

 @keshav-nangare  Can you test again?

**Comment by keshav-nangare** [comment]
@lgoltz 

The issue fixed and showing the result in detail HTML page.


But, the current working branch is failing with Maven Unit test:**`testGenerateEarlReport`**

**Comment by lgoltz** [comment]
> But, the current working branch is failing with Maven Unit test:testGenerateEarlReport

Should be fixed with https://github.com/opengeospatial/teamengine/commit/8fefc6c6cc6c42842fc566c3faf45520bd2744d1

**Comment by lgoltz** [comment]
@dstenger Please review notes in https://github.com/opengeospatial/teamengine/issues/319#issuecomment-377217091 and create new tickets, if required.

**Comment by keshav-nangare** [comment]
@dstenger 

I have tested the feature branch and worked successfully with CTL and TestNG test-suites.

Tested Environment: 

OS: Windows 8.1
JAVA: 1.8
ETS: gml32 1.26 and wms13 1.23-SNAPSHOT
