### ISSUE TITLE
Change URLs used in EARL Report

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine#326]
Currently the value "http://cite.opengeospatial.org/inheritedFailure" is used to mark an assertion as inheritedFailure. 
The EARL vocabulary provides e.g.  "http://www.w3.org/ns/earl#passed" for passed tests. The values should be more consistent to improve the transformation from EARL to the new HTML report.

Proposal for the example: http://cite.opengeospatial.org/earl#inheritedFailure

**Comment by lgoltz** [comment]
URL for InheritedFailure was already fixed: https://github.com/opengeospatial/teamengine/commit/149d8278f5d89fedd54a54ee7c586a9e7742bd96

**Comment by keshav-nangare** [comment]
@lgoltz 

You are right!! The result status value should be consistent.

Instead of changing the value of all the properties we can just add text **`earl#`** to the NS_URI then it will reflect in each result.

Below is the line:

https://github.com/opengeospatial/teamengine/blob/149d8278f5d89fedd54a54ee7c586a9e7742bd96/teamengine-spi/src/main/java/com/occamlab/te/spi/vocabulary/CITE.java#L23

We can do change here with value E.g. **`"http://cite.opengeospatial.org/earl#"`**

Instead of https://github.com/opengeospatial/teamengine/blob/149d8278f5d89fedd54a54ee7c586a9e7742bd96/teamengine-spi/src/main/java/com/occamlab/te/spi/vocabulary/CITE.java#L65

**Comment by lgoltz** [comment]
@keshav-nangare I totally agree with you. 
The changed line was only for a quick fix to handle also the inherited failures. And to break nothing else...

**Comment by keshav-nangare** [comment]
Ohh. Ok.

We can change that test status value to keep consistency of result.

**Comment by keshav-nangare** [comment]
I have updated the cite:namespace from "http://cite.opengeospatial.org/" ===>> "http://cite.opengeospatial.org/earl#".

The changes are successfully tested with the teamengine and ets.

Tested with:
- Teamengine: 5.3-SNAPSHOT
- ets-gml32 : 1.26-SNAPSHOT   ==> [Result](https://github.com/opengeospatial/teamengine/files/1915100/s0424.zip)

- ets-wms13 : 1.23-SNAPSHOT  ==> [Result](https://github.com/opengeospatial/teamengine/files/1915098/s0423.zip)

**Comment by keshav-nangare** [comment]
@lgoltz 

Please review the changes.

**Comment by dstenger** [comment]
@keshav-nangare 
You changed the namespace of prefix cite to "http://cite.opengeospatial.org/earl#".
This was not intended.

Instead, the value of earl:resource shall be changed to be more consistent. E.g. (this example is correct)
```
<earl:outcome rdf:resource="http://www.w3.org/ns/earl#passed"/>
```
"http://cite.opengeospatial.org/inheritedFailure" was already changed to "http://cite.opengeospatial.org/earl#inheritedFailure" (first improvement).

Also, other resources shall be checked if resource value can be improved.

**Comment by keshav-nangare** [comment]
Updated with this commit: 2dfc6ea4584dcd1fe2ac2fb44048e6b5708a7cd9 [PR: #332]
