### ISSUE TITLE
REST interface: Wrong media type is returned when using Firefox browser

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#373]
I am requesting
GET http://cite.opengeospatial.org/te2/rest/suites/wfs20/1.30/run?wfs=http://cite.deegree.org/deegree-webservices-3.4.0/services/wfs200?service=WFS%26request=GetCapabilities
with Firefox browser.
The Accept header is: `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`

Returned media type is EARL (RDF/XML) (Content-Type: `application/rdf+xml; qs=0.75;charset='utf-8'`).

Why is EARL returned although browser requests application/xml as media type with highest priority which is supported?

**Comment by dstenger** [comment]
Code which determines media type: https://github.com/opengeospatial/teamengine/blob/6ff9b6abb3469911ff88b8d5b02a75d180874a54/teamengine-spi/src/main/java/com/occamlab/te/spi/executors/testng/TestNGExecutor.java#L157

This code does not consider the quality (`q`). Thus, because of `*/*;q=0.8` EARL is returned.

If Accept header is set to `text/html,application/xhtml+xml,application/xml;q=0.9`, application/xml is returned (as expected).

Thus, evaluation of `q` should be implemented.

**Comment by keshav-nangare** [comment]
@dstenger 

I did the new implementation for REST API and which will handle all scenario.

Following are the scenario's I have tested:


Accept-Header | Expected Result | Actual Result
-- | -- | --
Empty | RDF | XML
application/rdf+xml | RDF | RDF
application/xml | XML | XML
application/zip | ZIP | ZIP
application/rdf+xml & application/xml | RDF | RDF
application/xml & application/zip | XML | XML
application/rdf+xml & application/zip | RDF | RDF
`*/*` | RDF | RDF
text/xml & application/json | Throw exception | 406: Not acceptable MediaType: [text/html, application/json]


### REST API executed via browsers:
 

Browser | Accept Headers | Result
-- | -- | -- |
Chrome | `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8` | XML
FireFox | `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8` | XML


Fixed with this PR #383
