### ISSUE TITLE
Incorrect verdict count in console summary

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#44]
Need to check if the reported issue [1] is a TEAM Engine issue

[1] http://lists.opengeospatial.org/pipermail/cite-forum/2014-July/001319.html

**Comment by keshav-nangare** [comment]
I have investigated this issue with the teamengine  version 4.5  and wfs 1.1.0-1.26-SNAPSHOT.

I have executed the WFS1.1.0 test, the summary test report is showing the correct result as expected and I have cross verified count with the testlist.xml result file which is present in the TE_BASE log directory. 

![summary_result](https://cloud.githubusercontent.com/assets/14732650/11981727/35443d74-a9cb-11e5-928e-c6de3331c791.png)

This issue is not reproduced now.
