### ISSUE TITLE
TestNG results includes reporter output for multiple test runs

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#47]
When using the REST API, the <reporter-output> element in the TestNG results contains info about multiple test runs, not just the most recent one. For example, upon executing the KML and GML test suites this appeared in the report:

```
    <reporter-output>  
      <line>Test suite parameters:</line>  
      <line>  
    {ics=2, iut=https://developers.google.com/kml/documentation/KML_Samples.kml}  
      </line>  
      <line>  
    Initial test run parameters: {xsd=, gml=file:///W:/2013-11-27DONLON.xml, sch=}  
      </line>  
      <line>Success? true</line>  
      <line>  
    Test run directory: C:\testng\0a5a2e33-9838-4d3f-8011-b0f9bbd64bb6  
      </line>  
    </reporter-output>

```

It contains output from **both** test runs. So perhaps the TestNG Reporter API is not thread safe.
[Originally reported in the OGC CITE issue tracker: issue #910](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=910)  

_Opened: 2013-12-05 13:31:50_

**Comment by bermud** [comment]
@rjmartell, @keshav-nangare  do we still have issues with TestNG Reporter API not being thread safe?

**Comment by bermud** [comment]
@keshav-nangare, please check if we still have this issue?

**Comment by keshav-nangare** [comment]
This issue is not reproducible now.

I have tested with the gml32 and kml22 using jmeter.

![image](https://cloud.githubusercontent.com/assets/14732650/21006076/4dab8100-bd5d-11e6-9c91-48bcd6746ea4.png)


Output: 

gml32: 

![image](https://cloud.githubusercontent.com/assets/14732650/21006161/9c148738-bd5d-11e6-9009-c6de37a77d26.png)

kml22:

![image](https://cloud.githubusercontent.com/assets/14732650/21006184/c85bfe2a-bd5d-11e6-8590-7d11454e4168.png)
