### ISSUE TITLE
Unit test TEPathTest fails

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#522]
**Describe the bug**
Current master of TEAM Engine cannot be built as unit test TEPathTest is failing:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in com.occamlab.te.util.TEPathTest
com.occamlab.te.util.TEPathTest  Time elapsed: 0.002 sec  <<< ERROR!
java.lang.NullPointerException
	at com.occamlab.te.util.TEPathTest.initialize(TEPathTest.java:75)
```

**To Reproduce**
1. Check out source code.
2. Execute `mvn clean install`.

**Expected behavior**
Build shall finish successfully.

**Comment by bpross-52n** [comment]
With the new path validation in place, two additional environment variables will have to be set:
TE_BASE=can be an empty directory
TE_BUILD=root of the Teamengine Java project
Otherwise, certain resources cannot be accessed by the tests. I will add documentation for this in the installation.html, if that is ok.
