### ISSUE TITLE
Create best practice documentation for failures caused by nested CTL tests

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#560]
**Is your feature request related to a problem? Please describe.**
Problem is described in https://github.com/opengeospatial/ets-wcs20/issues/113.

**Describe the solution you'd like**
Unit tests shall reflect the problem described in https://github.com/opengeospatial/ets-wcs20/issues/113.
Optionally, a new issue for a fix is created.

**Comment by bpross-52n** [comment]
The observed behavior is caused by a grouping of multiple tests in one test which also contains assertions. If this is the case, the assertions are not displayed correctly. It was discussed to create additional documentation on how to design tests in a way that the assertions and reasons of failures are displayed correctly.

**Comment by dstenger** [comment]
Documentation shall be updated in file https://github.com/opengeospatial/teamengine/blob/master/src/site/markdown/ctl.md.
