### ISSUE TITLE
In Teamengine Web-Application the 'stop' button in the header breaks the test rather than stopping it 

### ISSUE THREAD

**Issue by tanvi-shah** [opengeospatial/teamengine#59]

**Comment by upendra-sachan** [comment]
Yes, It is a issue for all test when stopping the test from the upper right stop. The stop button at bottom of the test works fine. Because when we click upper right stop it call this method:

if (operation.equals("Stop")) {
                response.setContentType("text/xml");
                TECore core = (TECore) session.getAttribute("testsession");
                if (core != null) {
                    core.stopThread();
                    session.removeAttribute("testsession");
                    out.println("<stopped/>");
                } else {
                    out.println("<message>Could not retrieve core object</message>");
                }
            }

Which actually sleeps the thread infinitely. We cant get the test status recordings at this place, since tests run in respective projects.

If bottom stop button is not present, we'll call the method which are calling right now for upper stop testing button, but when bottom stop testing button is present we use following solution:
 We can trigger the method for bottom stop test button from upper stop test button. So for this we can apply this solution:
Give a common id("stopTest") to all stop button at bottom of the test.
Trigger this button from upper right stop button for click event.
After clicking upper right stop button it automatically internally call bottom stop button and apply all operation.

**Comment by bermud** [comment]
Fixed with: https://github.com/opengeospatial/teamengine/commit/9539472571fceb938fad6c094e32c50dabaed000
