### ISSUE TITLE
Error message not shown in TestNG report

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#71]
The error message corresponding to a failing test method is not displayed in the TestNG report. For example, running the GML validator against the AIXM 5.1 schema produces the following report:

![gml-no-error](https://cloud.githubusercontent.com/assets/1653506/5320440/f97cc820-7c66-11e4-92a3-0fabffc60f30.png)

However, the message does appear in the raw TestNG results:

```     
<exception class="java.lang.AssertionError">
  <message>
    <![CDATA[Property value has minOccurs = 0. Property type definition must contain the 
@xlink:href attribute: {http://www.aixm.aero/schema/5.1}FeatureMetadataPropertyType 
expected object to not be null]]>
  </message>
</exception>
```

In TEAM-engine 4.0.5 the error message was displayed:

![gml-error](https://cloud.githubusercontent.com/assets/1653506/5320491/6f78ebd0-7c67-11e4-9807-67637f6110ab.png)

The regression was likely introduced by PR #43.

**Comment by tanvi-shah** [comment]
Hi Richard

Could you please send me the XML which you tested against the GML validator. We tested with the XML's that we had and we weren't getting blank reason for failure. Hence will need the XML you tested to reproduce the issue. Please see the attached screen shots.
![screenshot from 2014-12-24 14_40_10-2](https://cloud.githubusercontent.com/assets/7500215/5629605/7dda13ec-95db-11e4-868a-e23efa223241.png)
![screenshot from 2014-12-24 14_39_40-2](https://cloud.githubusercontent.com/assets/7500215/5629606/8358caca-95db-11e4-8866-b8bc8df4e327.png)
Also we have modified the screenshot so that java.language.Assertion.Error doesn't appear in the reason for failure.

**Comment by rjmartell** [comment]
Tanvi,

I ran the current GML test suite release (r18) against the AIXM 5.1 application schema. It's available from the AIXM web site here: http://www.aixm.aero/gallery/content/public/AIXM51/AIXM-5-1-20100201-xsd.zip.

Note: I see you were running r14. The latest ETS release can be obtained from [GitHub](https://github.com/opengeospatial/ets-gml32).
